CREATE DATABASE BDProjekt
GO
USE BDProjekt
GO
CREATE TABLE REPREZENTACJA(
	IDREPREZENTACJA INT PRIMARY KEY
	,NAZWA			CHAR(40) NOT NULL
)
GO
IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'MECZ')) 
	BEGIN 
			PRINT 'Tabela ZAWODNIK MECZ ISTNIEJE w dbo.DBProjekt UWAGA'
	END
ELSE
	BEGIN
			PRINT 'Tworzenie tabeli  MECZ w dbo.DBProjekt'
			CREATE TABLE MECZ(
	
			IDMECZ		INT PRIMARY KEY IDENTITY(1,1)
			,DATAW		DATETIME DEFAULT GETDATE()
			,GOSPODARZ_ID	INT NOT NULL
			,GOSC_ID		INT NOT NULL
			,BRAMKI_GOSP	INT 
			,BRAMKI_GOSC	INT
			,FOREIGN KEY (GOSPODARZ_ID) REFERENCES REPREZENTACJA(IDREPREZENTACJA)
			,FOREIGN KEY (GOSC_ID) REFERENCES REPREZENTACJA(IDREPREZENTACJA)
		)
	END
GO




IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'ZAWODNIK')) 
	BEGIN 
			PRINT 'Tabela ZAWODNIK istnieje w dbo.DBProjekt UWAGA'
	END
ELSE
	BEGIN
			PRINT 'Tworzenie tabeli ZAWODNIK w dbo.DBProjekt'
			CREATE TABLE ZAWODNIK(
		IDZAWODNIKA	INT PRIMARY KEY IDENTITY(1,1)
		,NAZWISKO	CHAR(30) NOT NULL
		,IMIE		CHAR(30) NOT NULL
		,NUMER		INT NOT NULL CHECK (NUMER BETWEEN 1 AND 99)
		,WIEK		INT	NOT NULL 
		,IDREPREZENTACJA INT NOT NULL
		,PLEC		CHAR(1) 
		,FOREIGN KEY (IDREPREZENTACJA) REFERENCES REPREZENTACJA(IDREPREZENTACJA)
		)
	END
GO

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'STATYZAW')) 
	BEGIN 
			PRINT 'Tabela STATYZAW istnieje w dbo.DBProjekt UWAGA'
	END
ELSE
	BEGIN
			PRINT 'Tworzenie tabeli STATYZAW w dbo.DBProjekt'
			CREATE TABLE STATYZAW(
		IDDANE		INT PRIMARY KEY IDENTITY(1,1)
		,IDMECZ		INT NOT NULL
		,IDZAWODNIKA	INT NOT NULL
		,XG		DECIMAL(6, 2) DEFAULT 0
		,XA		DECIMAL(6, 2) DEFAULT 0
		,GOLE	INT DEFAULT 0
		,ASYSTY	INT DEFAULT 0
		,OCENA	DECIMAL(6,2) DEFAULT 0
		,MINUTY INT	DEFAULT 90
		,FOREIGN KEY (IDZAWODNIKA) REFERENCES ZAWODNIK(IDZAWODNIKA)
		,FOREIGN KEY (IDMECZ) REFERENCES MECZ(IDMECZ)
		)
	END
GO

--- usuwanie statyzaw
DROP TABLE STATYZAW

--- usuwanie ZAWODNIK
DROP TABLE STATYZAW
DROP TABLE ZAWODNIK

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'MECZ')) 
	BEGIN 
			DROP TABLE STATYZAW
			DROP TABLE ZAWODNIK
			DROP TABLE MECZ
			PRINT 'Usuwanie Tabeli MECZ i tabel powiazanych: z dbo.DBprojekt'
	END
ELSE
	BEGIN
			PRINT 'BRAK TABELI MECZ w bazie dbo.DBProjekt'
	END
GO


---- usuwanie tabeli reprezentacja
IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'REPREZENTACJA')) 
	BEGIN 
			DROP TABLE STATYZAW
			DROP TABLE ZAWODNIK
			DROP TABLE MECZ
			DROP TABLE REPREZENTACJA
			PRINT 'Usuwanie Tabeli REPREZENTACJA i tabel powiazanych: z dbo.DBprojekt'
	END
ELSE
	BEGIN
			PRINT 'BRAK TABELI REPREZENTACJA w bazie dbo.DBProjekt'
	END
GO





